Args = --enable-monitoring=jmxclient \
       --features=io.github.yagipass.ajmx.nativeimage.AjmxFeature \
       -H:-ParseRuntimeOptions \
       -H:+UnlockExperimentalVMOptions \
       -H:ServiceLoaderFeatureExcludeServiceProviders=sun.awt.www.content.MultimediaContentHandlers \
       -H:-UnlockExperimentalVMOptions
