name: gradle-deps

on:
  pull_request:
    paths:
      - gradle/libs.versions.toml
      - "**.gradle.kts"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  update:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
      - uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      - name: Let bubblewrap create user namespaces for the update script
        run: sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
      - run: "$(nix build --no-link --print-out-paths .#ajmx.mitmCache.updateScript)"
      - run: |
          git diff --quiet && exit 0
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -am 'build(nix): update ajmx deps.json'
          git push
